console.log('test');

var psiPeople = [
  {name: "Millie", springBday: true},
  {name: "Dev", springBday: false},
  {name: "Abby", springBday: true},
  {name: "Alayna", springBday: true},
  {name: "Amy", springBday: true},
  {name: "Barb", springBday: true},
  {name: "Ben", springBday: true},
  {name: "Charlie", springBday: true},
  {name: "Colin", springBday: true},
  {name: "Droo", springBday: true},
  {name: "Amal", springBday: true},
  {name: "Jim", springBday: true},
  {name: "Jorge", springBday: true},
  {name: "Kara", springBday: true},
  {name: "Matt", springBday: true},
  {name: "Neota", springBday: true},
  {name: "Ryan", springBday: true},
  {name: "Sean", springBday: true},
  {name: "Tessa", springBday: true},
  {name: "Millie", springBday: true},
  {name: "Zee", springBday: true},
];
